schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "434fb35b620c7d91e4ed6d2c57dcbd"
        X-Exclude-Invalid: true
documents: './src/datocms/**/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unkown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
    config:
      namingConvention:
        enumValues: './pascalCaseWithUnderscores'